name: Deploy to heroku

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Heroku Login
        run: |
          cd docker
          sed -Ei "s/login/login "${{secrets.HEROKU_EMAIL}}"/g" .netrc
          sed -Ei "s/password/password "${{secrets.HEROKU_API_KEY}}"/g" .netrc
          mv .netrc ~/.netrc
          cat ~/.netrc
